The ``7-base_geometry`` module
======================

Using ``BaseGeometry``
---------------------

>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

>>> geo = BaseGeometry()
>>> geo.integer_validator("hello", 22)
>>> geo = BaseGeometry(None)
Traceback (most recent call last):
TypeError: object() takes no parameters

>>> geo = BaseGeometry()
>>> geo = BaseGeometry("hello")
Traceback (most recent call last):
TypeError: object() takes no parameters

>>> geo.area()
Traceback (most recent call last):
Exception: area() is not implemented

>>> geo.area("56")
Traceback (most recent call last):
TypeError: area() takes 1 positional argument but 2 were given

>>> geo.integer_validator()
Traceback (most recent call last):
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

>>> geo.integer_validator("56", 5, 33)
Traceback (most recent call last):
TypeError: integer_validator() takes 3 positional arguments but 4 were given

>>> geo.integer_validator("hello", 0)
Traceback (most recent call last):
ValueError: hello must be greater than 0

>>> geo.integer_validator("hello", "Luz")
Traceback (most recent call last):
TypeError: hello must be an integer

>>> geo.integer_validator("hello", -12.55)
Traceback (most recent call last):
TypeError: hello must be an integer

>>> geo.integer_validator("e", 1e300)
Traceback (most recent call last):
TypeError: e must be an integer

>>> geo.integer_validator("a", [5, 2])
Traceback (most recent call last):
TypeError: a must be an integer

>>> geo.integer_validator("g", -1)
Traceback (most recent call last):
ValueError: g must be greater than 0

>>> geo.integer_validator("a", 12.55)
Traceback (most recent call last):
TypeError: a must be an integer

>>> geo.integer_validator("s", None)
Traceback (most recent call last):
TypeError: s must be an integer

>>> geo.integer_validator("i", NaN)
Traceback (most recent call last):
NameError: name 'NaN' is not defined

>>> geo.integer_validator("i", (1, 2))
Traceback (most recent call last):
TypeError: i must be an integer

>>> geo = BaseGeometry(None)
Traceback (most recent call last):
TypeError: object() takes no parameters

>>> geo.integer_validator("e", int(10.55))

>>> geo.integer_validator(33, {'e': 5})
Traceback (most recent call last):
TypeError: 33 must be an integer

>>> geo.integer_validator("luz", {3, 2})
Traceback (most recent call last):
TypeError: luz must be an integer

>>> geo.integer_validator("luz", [88])
Traceback (most recent call last):
TypeError: luz must be an integer
